version: '3.5'
services:

  nginx:
    build: docker/nginx
    ports:
      - "8080:80"
    networks:
      - service
    depends_on:
      - core-service-1
      - core-service-2
      - core-service-3

  core-service-1:
    container_name: core-service-1
    image: kanutan93/core-service:1.0.3
    networks:
      - service
    env_file:
      - ./docker/env/core-service.env
    volumes:
      - ./docker/images:/opt/images

  core-service-2:
    container_name: core-service-2
    image: kanutan93/core-service:1.0.3
    networks:
      - service
    env_file:
      - ./docker/env/core-service.env
    volumes:
      - ./docker/images:/opt/images

  core-service-3:
    container_name: core-service-3
    image: kanutan93/core-service:1.0.3
    networks:
      - service
    env_file:
      - ./docker/env/core-service.env
    volumes:
      - ./docker/images:/opt/images

  image-processing-service-1:
    container_name: image-processing-service-1
    image: kanutan93/image-processing-service:1.0.8
    networks:
      - service
    restart: always
    env_file:
      - ./docker/env/image-processing-service.env
    volumes:
      - ./docker/images:/opt/images

  image-processing-service-2:
    container_name: image-processing-service-2
    image: kanutan93/image-processing-service:1.0.8
    networks:
      - service
    restart: always
    env_file:
      - ./docker/env/image-processing-service.env
    volumes:
      - ./docker/images:/opt/images

  image-processing-service-3:
    container_name: image-processing-service-3
    image: kanutan93/image-processing-service:1.0.8
    networks:
      - service
    restart: always
    env_file:
      - ./docker/env/image-processing-service.env
    volumes:
      - ./docker/images:/opt/images

  haproxy:
    image: haproxy
    networks:
      - service
    ports:
      - "5000:5000"
    volumes:
      - ./docker/haproxy:/usr/local/etc/haproxy
    depends_on:
      - pg-slave-1
      - pg-slave-2

  pg-master:
    container_name: pg-master
    image: postgres
    networks:
      - service
    restart: always
    environment:
      POSTGRES_DB: 'dam'
      POSTGRES_USER: 'dam_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/pg-master:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg-slave-1:
    container_name: pg-slave-1
    image: postgres
    networks:
      - service
    restart: always
    environment:
      POSTGRES_DB: 'dam'
      POSTGRES_USER: 'dam_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/pg-slave-1:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - pg-master

  pg-slave-2:
    container_name: pg-slave-2
    image: postgres
    networks:
      - service
    restart: always
    environment:
      POSTGRES_DB: 'dam'
      POSTGRES_USER: 'dam_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/postgres/pg-slave-2:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    depends_on:
      - pg-master

  redis:
    container_name: redis
    image: redis
    networks:
      - service
    restart: always
    environment:
      REDIS_PASSWORD: 'password'
    ports:
      - "6379:6379"

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks:
      - service
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    networks:
      - service
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091,PLAINTEXT_INTERNAL://localhost:29091
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    ports:
      - "9091:9091"
      - "29091:29091"
    depends_on:
      - zookeeper

  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:latest
    networks:
      - service
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    ports:
      - "9092:9092"
      - "29092:29092"

  kafka-3:
    container_name: kafka-3
    image: confluentinc/cp-kafka:latest
    networks:
      - service
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9093,PLAINTEXT_INTERNAL://localhost:29093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    ports:
      - "9093:9093"
      - "29093:29093"

  kafka-exporter:
    container_name: kafka-exporter
    image: danielqsj/kafka-exporter
    networks:
      - service
    command: [ "--kafka.server=kafka:9092", "--kafka.server=kafka-2:9092", "--kafka.server=kafka-3:9092" ]
    ports:
      - "9308:9308"
    depends_on:
      - kafka
      - kafka-2
      - kafka-3

  prometheus:
    image: prom/prometheus
    volumes:
      - "./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - service
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    networks:
      - service
    restart: always
    ports:
      - '3000:3000'

networks:
  service:
    driver: bridge

volumes:
  healthcheck-volume:
