scrape_configs:
  - job_name: 'dam_core-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: '15s'
    static_configs:
      - targets: ['core-service-1:8080', 'core-service-2:8080', 'core-service-3:8080']
  - job_name: 'dam_image-processing-service'
    metrics_path: '/'
    scrape_interval: '15s'
    static_configs:
      - targets: ['image-processing-service-1:9309', 'image-processing-service-2:9309', 'image-processing-service-3:9309']
  - job_name: 'dam_kafka'
    metrics_path: '/metrics'
    scrape_interval: '15s'
    static_configs:
      - targets: ['kafka-exporter:9308']